### ISSUE TITLE
Design: Research 1

### ISSUE THREAD

**Issue by ncsQuan** [ai-conversation-coach/convo-guru#13]
- conduct competitive analysis
- conduct surveys/interviews
- create user personas
Collaborate with your design counterpart

**Comment by nninanguyenn** [comment]
Conduct competitive analysis:
1. Duolingo
- Strengths: Well-established language learning platform with a large user base.
- Weaknesses: Focuses more on structured language learning rather than free-form conversation practice.
- Opportunities: Could integrate AI-driven conversation coaching features to enhance speaking practice for language learners.
- Threats: New users in the language learning space offering specialized conversation coaching features could pose a threat to Duolingo's market dominance.

2. Talkspace:
- Strengths: Talkspace provides therapy and counseling services, which could attract users seeking support for communication-related issues such as social anxiety or public speaking anxiety.
- Weaknesses: Talkspace's focus on therapy may limit its suitability for users seeking structured conversation practice and coaching.
- Opportunities: Talkspace could introduce specialized coaching programs or add-on services focusing on improving communication skills for users without clinical mental health needs.
- Threats: Specialized conversation coaching apps offering similar services could compete with Talkspace for users seeking support with communication skills.


Conduct surveys/interviews:
- Challenges in Communication: The most commonly reported challenges include feeling nervous or anxious in social situations, difficulty expressing thoughts and ideas clearly, and struggling to keep conversations flowing smoothly. Many respondents also noted uncertainty about how to respond to unexpected questions or comments as a significant challenge.
- Confidence in Communication Skills: On a scale of 1 to 5, respondents rated their confidence in communication skills at an average of 3.2, indicating moderate confidence overall.
- Handling Challenging Communication Situations: Respondents reported using a variety of strategies to handle challenging communication situations, including trying to think of something to say on the spot, seeking advice from friends or family, and, in some cases, avoiding the conversation or situation altogether.
- Desired Features in an AI Conversation Coach App: The most important features identified by respondents include providing suggestions to keep conversations flowing, personalized coaching sessions tailored to individual communication needs, and practice exercises to improve conversational skills. 
- Likelihood of Using an AI Conversation Coach App: Respondents expressed varying levels of interest in using an AI conversation coach app to improve their communication skills, with a majority indicating that they were either very likely or somewhat likely to use such an app.
- Additional Feedback: Many respondents provided additional feedback, expressing interest in features such as speech recognition, role-playing scenarios, and compatibility with multiple languages


Create user personas:
1. Sophia - Socially Anxious Student
- Background: Sophia is a 21-year-old college student.
- Communication Challenges: Sophia experiences significant social anxiety. She often struggles to initiate conversations and find topics to discuss, leading to feelings of isolation and self-doubt.
- Communication Goals: Sophia wants to improve her confidence in social situations and learn how to keep conversations flowing smoothly.
- Expectations from the App: Sophia is looking for an AI conversation coach app that can provide guidance on demand, offer personalized coaching sessions, and create a supportive environment for practicing conversational skills. She values convenience and accessibility, preferring an app that she can use discreetly on her phone whenever she needs a confidence boost.

2. David - The Career-Driven Professional
- Background: David is a 32-year-old marketing manager at a tech company. He leads a team of marketers and frequently interacts with clients and stakeholders.
- Communication Challenges: David is confident in his professional abilities but struggles with public speaking and delivering presentations. He often feels nervous before important meetings or client pitches and worries about stumbling over his words or forgetting key points.
- Communication Goals: David aims to improve his communication skills to advance in his career. He wants to feel more confident when speaking in front of others and to convey his ideas clearly.
- Expectations from the App: David is seeking an AI conversation coach app that can provide real-time feedback on his communication performance, offer personalized coaching sessions tailored to his professional needs, and help him practice delivering presentations in a virtual setting. He values practicality and results, looking for an app that can help him achieve tangible improvements in his communication skills.
